print("Hello World")
print("Hello Again")
print()
print("Hello BootCamper's Collective!")
print("My name is (your name here).")
print()
print("'print()' is a python method.")
print("Python Docs are here --> https://docs.python.org/3/")
print()
print("This line has nested 'single' quotes.")
print('This line has nested "double quotes".')
print()
print('Now toggle into your terminal and type: python3 ex1.py')
print('This symbol --> # <-- is called an "octothorpe", a "mesh", "pound", or "hash".')

# print("Remove the hash from the beginning of this line, so the python interpreter can print this text.")
# <-- this hash tells python to comment.
