print("Hello World.")
print("Hello again.")
print()
print("Hello BCC.")
print("My name is Andy.")
print()
print("print() is a python method.")
print("Python Documentation --> https://docs.python.org/3/")
print()
print("These are -->'<--single quotes-->'<--.")
print('These are "double quotes" in single quotes.')
print("Type: 'python3 ex1.py' in terminal to run this program.")
# print("Un-comment this line to have it print on execution.")