print("Hello World.")
print("Hello again.")
print()
print("Hello Python Weekly Meetup©")
print("My name is Andy.")
print()
print("Py docs @ --> https://docs.python.org/3 <--")
print("RUN ex1.py in terminal with this command --> python3 ex1.py <--")
print()
print("\"single ->'quotes' in double quotes ->\"")
print('\'double ->"quotes" in single quotes ->\'')
# print()
print("If you read this, I un-commented this line.")