print("Hello World")
print("Hello again.\n")
print("Hello BCC!")
print("My name is Andy.\n")
print("single 'quotes' <-- in double quotes")
print('double "quotes" <-- in single quotes\n')
print("Python docs @ --> https://docs/python.org/3")
print("Type --> python3 ex1.py <-- in terminal to run this program.\n")
# print("If you're reading this, it's because I un-commented the line.")